/*******************************************************************************
 * Université d’Aix Marseille (AMU) - Centre National de la Recherche Scientifique (CNRS)
 * Copyright 2014 AMU-CNRS All Rights Reserved.
 * 
 * These computer program listings and specifications, herein, are
 * the property of Université d’Aix Marseille and CNRS
 * shall not be reproduced or copied or used in whole or in part as
 * the basis for manufacture or sale of items without written permission.
 * For a license agreement, please contact:
 * <mailto: licensing@sattse.com> 
 * 
 * Author : Frank BULOUP
 * Institut des Sciences du Mouvement - franck.buloup@univ-amu.fr
 ******************************************************************************/
package analyse.resources;

import org.eclipse.jface.resource.ImageDescriptor;
import org.eclipse.jface.resource.ImageRegistry;
import org.eclipse.jface.resource.JFaceResources;
import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.widgets.Display;

public final class ImagesUtils {

	private static ImageRegistry imagesRegistry = null;
	
	public static void initialize(Display display) {
		if(imagesRegistry == null) {		
			imagesRegistry = JFaceResources.getImageRegistry();	
			ImageDescriptor analyseIconID = null;
			ImageDescriptor analyseIconSmallID = null;
			ImageDescriptor experimentsViewID = null;
			ImageDescriptor channelsViewID = null;
			ImageDescriptor messagesViewID = null;
			ImageDescriptor experimentIconID = null;
			ImageDescriptor subjectIconID = null;
			ImageDescriptor dataFileIconID = null;		
			ImageDescriptor newExperimentIconID = null;
			ImageDescriptor openExperimentIconID = null;
			ImageDescriptor closeExperimentIconID = null;
			ImageDescriptor importSubjectsIconID = null;
			ImageDescriptor deleteExperimentIconID = null;
			ImageDescriptor deleteSubjectIconID = null; 
			ImageDescriptor newExperimentBannerID = null;
			ImageDescriptor importSujectBannerID = null; 
			ImageDescriptor dataFileBannerID = null;
			ImageDescriptor renameBannerID = null;
			ImageDescriptor clearMessagesIconID = null;
			ImageDescriptor loadUnloadSubjectIconID = null;
			ImageDescriptor loadedSubjectIconDecoratorID = null;
			ImageDescriptor processEditorIconID = null;
			ImageDescriptor chartEditorIconID = null;
			ImageDescriptor chartBannerIconID = null;
			ImageDescriptor chartIconID = null;
			ImageDescriptor deleteChartIconID = null;
			ImageDescriptor signalsIconID = null;
			ImageDescriptor categoriesIconID = null;
			ImageDescriptor lockConsoleIconID = null;
			ImageDescriptor deleteProcessIconID = null;
			ImageDescriptor libraryIconID = null;
			ImageDescriptor functionIconID = null;
			ImageDescriptor deleteFunctionIconID = null;
			ImageDescriptor moveFunctionUpIconID = null;
			ImageDescriptor  moveFunctionDownIconID = null;
			ImageDescriptor saveIconID = null;
			ImageDescriptor  saveAllIconID = null;
			ImageDescriptor  printIconID = null;
			ImageDescriptor  undoIconID = null;
			ImageDescriptor  redoIconID = null;
			ImageDescriptor  cutIconID = null;
			ImageDescriptor  copyIconID = null;
			ImageDescriptor  pasteIconID = null;
			ImageDescriptor  deleteIconID = null;
			ImageDescriptor  runIconID = null;
			ImageDescriptor  fontIconID = null;
			ImageDescriptor  consoleViewIconID = null;
			ImageDescriptor  chartOptionsIconID = null;
			ImageDescriptor  chartLeftIconID = null;
			ImageDescriptor  chartRightIconID = null;
			ImageDescriptor  chartUpIconID = null;
			ImageDescriptor  chartDownIconID = null;
			ImageDescriptor  chartZoomInIconID = null;
			ImageDescriptor  chartZoomOutIconID = null;
			ImageDescriptor  adjustXAxisIconID = null;
			ImageDescriptor  adjustYAxisIconID = null;
			ImageDescriptor  adjustXYAxisIconID = null;
			ImageDescriptor  crossHairIconID = null;
			ImageDescriptor  markerIconID = null;
			ImageDescriptor  addMarkerIconID = null;
			ImageDescriptor  modifiedIconID = null;
			ImageDescriptor  exportWizardBannerID = null;
			ImageDescriptor  exportWizardIconID = null;
			ImageDescriptor  parameterIconID = null;
			ImageDescriptor  keywordIconID = null;
			ImageDescriptor  inputsIconID = null;
			ImageDescriptor  outputsIconID = null;
			ImageDescriptor  parametersIconID = null;
			ImageDescriptor  nextTrialIconID = null;
			ImageDescriptor  previousTrialIconID = null;
			ImageDescriptor  processBannerID = null;
			ImageDescriptor  newCategoryID = null;
			ImageDescriptor  newCategoryBannerID = null;
			ImageDescriptor  folderID = null;
			ImageDescriptor  newFolderBannerID = null;
			ImageDescriptor  helpID = null;
			ImageDescriptor  mainTopicID = null;
			ImageDescriptor  subTopicID = null;
			ImageDescriptor  subSubTopicID = null;
			ImageDescriptor  updateID = null;
			ImageDescriptor  removeMarkerTrialIconID = null;
			ImageDescriptor  removeFieldMarkersGroupIconID = null;
			ImageDescriptor  categoryViewIconID = null;
			ImageDescriptor  previewViewIconID = null;
			ImageDescriptor  addCategoryIconID = null;
			ImageDescriptor  saveBannerID = null;
			ImageDescriptor  stopIconID = null;
			ImageDescriptor  refreshIconID = null;
			ImageDescriptor  randomizeColorIconID = null;
			ImageDescriptor  clearChartIconID = null;
			ImageDescriptor  updateIconID = null;
			ImageDescriptor  showExperimentsMenuIconID = null;
			ImageDescriptor  collapseAllIconID = null;
			ImageDescriptor  expandAllIconID = null;
			ImageDescriptor  addIconID = null;
			ImageDescriptor  refactorIconID = null;
			ImageDescriptor  refactorBannerID = null;
			ImageDescriptor  changesIconID = null;
			ImageDescriptor  addFunctionIconID = null;
			ImageDescriptor  runProcessIconID = null;
			ImageDescriptor  errorIconDecoratorID = null;
			ImageDescriptor  warningIconDecoratorID = null;
			ImageDescriptor  checkProcessIconID = null;
			ImageDescriptor  fieldIconID = null;
			ImageDescriptor  newSignalIconID = null;
			ImageDescriptor  cheatSheetIconID = null;
			ImageDescriptor  analyseImageID = null;
			ImageDescriptor  experimentsViewImageID = null;
			ImageDescriptor  signalsViewImageID = null;
			ImageDescriptor  categoriesViewImageID = null;
			ImageDescriptor  previewSignalsViewImageID = null;
			ImageDescriptor  messagesViewImageID = null;
			ImageDescriptor  consoleViewImageID = null;
			ImageDescriptor  chartEditorViewImageID = null;
			ImageDescriptor  processEditorViewImageID = null;
			ImageDescriptor  eventsViewIconID = null;
			ImageDescriptor  axisIconID = null;
			ImageDescriptor axisBannerID = null;
			ImageDescriptor noteIconID = null;
			ImageDescriptor startServerIconID = null;
			ImageDescriptor disconnectUserIconID = null;
			ImageDescriptor connectServerIconID = null;
			ImageDescriptor importIconID = null;
			ImageDescriptor sharingViewIconID = null;
			ImageDescriptor stopServerIconID = null;
			ImageDescriptor experimentsSharingBannerID = null;
			ImageDescriptor ftpUserIconID = null;
			ImageDescriptor folderUpconID = null;
			ImageDescriptor functionConfigID = null;
			ImageDescriptor functionCodeID = null;
			ImageDescriptor signalFrequencyBannerID = null;
			ImageDescriptor switchLibraryID = null;
			ImageDescriptor newSubjectBannerID = null;
			ImageDescriptor AddColumnIconID = null;
			ImageDescriptor deleteColumnIconID = null;
			ImageDescriptor chartConfigurationIconID = null;


			analyseIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.ANALYSE_ICON));
			analyseIconSmallID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.ANALYSE_ICON_SMALL));
			experimentsViewID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.EXPERIMENTS_VIEW_ICON));
			channelsViewID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CHANNELS_VIEW_ICON));
			messagesViewID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.MESSAGES_VIEW_ICON));
			experimentIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.EXPERIMENT_ICON));
			subjectIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.SUBJECT_ICON));
			dataFileIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.DATAFILE_ICON));
			newExperimentIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.NEW_EXPERIMENT_ICON));
			openExperimentIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.OPEN_EXPERIMENT_ICON));
			closeExperimentIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CLOSE_EXPERIMENT_ICON));
			importSubjectsIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.IMPORT_SUBJECTS_ICON));
			deleteExperimentIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.DELETE_EXPERIMENT_ICON));
			deleteSubjectIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.DELETE_SUBJECT_ICON)); 
			newExperimentBannerID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.NEW_EXPERIMENT_BANNER));
			importSujectBannerID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.IMPORT_SUBJECT_BANNER));
			dataFileBannerID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.DATA_FILE_BANNER));
			renameBannerID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.RENAME_BANNER));
			clearMessagesIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CLEAR_MESSAGES_ICON));
			loadedSubjectIconDecoratorID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.LOADED_SUBJECT_ICON_DECORATOR));
			processEditorIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.PROCESS_EDITOR_ICON));
			chartEditorIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CHART_EDITOR_ICON));
			chartBannerIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.NEW_CHART_BANNER));
			chartIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CHART_ICON));
			deleteChartIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.DELETE_CHART_ICON));
			signalsIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.SIGNALS_ICON));
			categoriesIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CATEGORIES_ICON));
			lockConsoleIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.LOCK_CONSOLE_ICON));
			deleteProcessIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.DELETE_PROCESS_ICON));
			libraryIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.LIBRARY_ICON));
			functionIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.FUNCTION_ICON));
			deleteFunctionIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.DELETE_FUNCTION_ICON));
			moveFunctionUpIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.MOVE_FUNCTION_UP));
			moveFunctionDownIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.MOVE_FUNCTION_DOWN));
			saveIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.SAVE_ICON));
			saveAllIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.SAVE_ALL_ICON));
			printIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.PRINT_ICON));
			undoIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.UNDO_ICON));
			redoIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.REDO_ICON));
			cutIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CUT_ICON));
			copyIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.COPY_ICON));
			pasteIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.PASTE_ICON));
			deleteIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.DELETE_ICON));
			runIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.RUN_ICON));
			fontIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.FONT_ICON));
			consoleViewIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CONSOLE_VIEW_ICON));
			chartOptionsIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CHART_OPTIONS_ICON));
			chartLeftIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CHART_LEFT_ICON));
			chartRightIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CHART_RIGHT_ICON));
			chartUpIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CHART_UP_ICON));
			chartDownIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CHART_DOWN_ICON));
			chartZoomInIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CHART_ZOOM_IN_ICON));
			chartZoomOutIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CHART_ZOOM_OUT_ICON));
			adjustXAxisIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.ADJUST_X_AXIS_ICON));
			adjustYAxisIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.ADJUST_Y_AXIS_ICON));
			adjustXYAxisIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.ADJUST_XY_AXIS_ICON));
			crossHairIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CROSSHAIR_ICON));
			markerIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.MARKER_ICON));
			addMarkerIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.ADD_MARKER_ICON));
			modifiedIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.MODIFIED_SUBJECT_ICON_DECORATOR));
			exportWizardBannerID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.EXPORT_WIZARD_BANNER));
			exportWizardIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.EXPORT_WIZARD_ICON));
			parameterIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.PARAMETER_ICON));
			keywordIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.KEYWORD_ICON));
			inputsIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.INPUTS_ICON));
			outputsIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.OUTPUTS_ICON));
			parametersIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.PARAMETERS_ICON));
			nextTrialIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.NEXT_TRIAL_ICON));
			previousTrialIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.PREVIOUS_TRIAL_ICON));
			processBannerID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.NEW_PROCESS_BANNER));
			newCategoryID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.NEW_CATEGORY));
			newCategoryBannerID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.NEW_CATEGORY_BANNER));
			folderID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.FOLDER_ICON));
			newFolderBannerID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.NEW_FOLDER_BANNER));
			helpID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.HELP_CONTENT_ICON));
			mainTopicID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.MAIN_TOPIC_ICON));
			subTopicID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.SUB_TOPIC_ICON));
			subSubTopicID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.SUB_SUB_TOPIC_ICON));
			updateID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.UPDATE_BANNER));
			//loadUnloadSubjectIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.ANALYSE_ICON_SMALL));
			loadUnloadSubjectIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.LOAD_UNLOAD_SUBJECT_ICON));
			removeMarkerTrialIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.REMOVE_MARKER_TRIAL_ICON));
			removeFieldMarkersGroupIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.REMOVE_FIELD_MARKERS_GROUP_ICON));
			categoryViewIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CATEGORY_VIEW_ICON));
			previewViewIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.PREVIEW_VIEW_ICON));
			addCategoryIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.ADD_CATEGORY_ICON));
			saveBannerID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.SAVE_BANNER));
			stopIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.STOP_ICON));
			refreshIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.REFRESH_ICON));
			randomizeColorIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.RANDOMIZE_COLOR_ICON));
			clearChartIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CLEAR_CHART_ICON));
			updateIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.UPDATE_ICON));
			showExperimentsMenuIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.SHOW_EXPERIMENTS_MENU_ICON));
			collapseAllIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.COLLAPSE_ALL_ICON));
			expandAllIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.EXPAND_ALL_ICON));
			addIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.ADD_ICON));
			refactorIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.REFACTOR_ICON));
			refactorBannerID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.REFACTOR_BANNER));
			changesIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CHANGES_ICON));
			addFunctionIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.ADD_FUNCTION_ICON));
			runProcessIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.RUN_PROCESS_ICON));
			errorIconDecoratorID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.ERROR_ICON_DECORATOR));
			warningIconDecoratorID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.WARNING_ICON_DECORATOR));
			checkProcessIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CHECK_PROCESS_ICON));
			fieldIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.FIELD_ICON));
			newSignalIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.NEW_SIGNAL_ICON));
			cheatSheetIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CHEAT_SHEET_ICON));
			analyseImageID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.ANALYSE_IMAGE));
			experimentsViewImageID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.EXPERIMENTS_VIEW_IMAGE));
			signalsViewImageID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.SIGNALS_VIEW_IMAGE));
			categoriesViewImageID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CATEGORIES_VIEW_IMAGE));
			previewSignalsViewImageID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.PREVIEW_SIGNALS_VIEW_IMAGE));
			messagesViewImageID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.MESSAGES_VIEW_IMAGE));
			consoleViewImageID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CONSOLE_VIEW_IMAGE));
			chartEditorViewImageID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CHART_EDITOR_VIEW_IMAGE));
			processEditorViewImageID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.PROCESS_EDITOR_VIEW_IMAGE));
			eventsViewIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.EVENTS_VIEW_ICON));
			axisIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.AXIS_ICON));
			axisBannerID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.AXIS_BANNER));
			noteIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.NOTE_ICON));
			startServerIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.START_SERVER_ICON));
			disconnectUserIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.DISCONNECT_USER_ICON));
			connectServerIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CONNECT_SERVER_ICON));
			importIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.IMPORT_ICON));
			sharingViewIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.SHARING_VIEW_ICON));
			stopServerIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.STOP_SERVER_ICON));
			experimentsSharingBannerID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.EXPERIMENTS_SHARING_BANNER));
			ftpUserIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.FTP_USER_ICON));
			folderUpconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.FOLDER_UP_ICON));
			functionConfigID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.FUNCTION_CONFIG));
			functionCodeID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.FUNCTION_CODE));
			signalFrequencyBannerID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.SIGNAL_FREQUENCY_BANNER));
			switchLibraryID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.SWITCH_LIBRARY_ICON));
			newSubjectBannerID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.NEW_SUBJECT_BANNER));
			AddColumnIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.ADD_COLUMN_ICON));
			deleteColumnIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.DELETE_COLUMN_ICON));
			chartConfigurationIconID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.CHART_CONFIGURATION_ICON));
			 
			imagesRegistry.put(IImagesKeys.ANALYSE_ICON, analyseIconID);
			imagesRegistry.put(IImagesKeys.ANALYSE_ICON_SMALL, analyseIconSmallID);
			imagesRegistry.put(IImagesKeys.EXPERIMENTS_VIEW_ICON, experimentsViewID);
			imagesRegistry.put(IImagesKeys.CHANNELS_VIEW_ICON, channelsViewID);
			imagesRegistry.put(IImagesKeys.MESSAGES_VIEW_ICON, messagesViewID);
			imagesRegistry.put(IImagesKeys.EXPERIMENT_ICON, experimentIconID);
			imagesRegistry.put(IImagesKeys.SUBJECT_ICON, subjectIconID);
			imagesRegistry.put(IImagesKeys.DATAFILE_ICON, dataFileIconID);
			imagesRegistry.put(IImagesKeys.NEW_EXPERIMENT_ICON, newExperimentIconID);
			imagesRegistry.put(IImagesKeys.OPEN_EXPERIMENT_ICON, openExperimentIconID);
			imagesRegistry.put(IImagesKeys.CLOSE_EXPERIMENT_ICON, closeExperimentIconID);
			imagesRegistry.put(IImagesKeys.IMPORT_SUBJECTS_ICON, importSubjectsIconID);
			imagesRegistry.put(IImagesKeys.DELETE_EXPERIMENT_ICON, deleteExperimentIconID);
			imagesRegistry.put(IImagesKeys.DELETE_SUBJECT_ICON, deleteSubjectIconID);
			imagesRegistry.put(IImagesKeys.NEW_EXPERIMENT_BANNER, newExperimentBannerID);
			imagesRegistry.put(IImagesKeys.IMPORT_SUBJECT_BANNER, importSujectBannerID);
			imagesRegistry.put(IImagesKeys.DATA_FILE_BANNER, dataFileBannerID);
			imagesRegistry.put(IImagesKeys.RENAME_BANNER, renameBannerID);
			imagesRegistry.put(IImagesKeys.CLEAR_MESSAGES_ICON, clearMessagesIconID);
			imagesRegistry.put(IImagesKeys.PROCESS_EDITOR_ICON, processEditorIconID);
			imagesRegistry.put(IImagesKeys.CHART_EDITOR_ICON, chartEditorIconID);
			imagesRegistry.put(IImagesKeys.NEW_CHART_BANNER, chartBannerIconID);
			imagesRegistry.put(IImagesKeys.CHART_ICON, chartIconID);
			imagesRegistry.put(IImagesKeys.DELETE_CHART_ICON, deleteChartIconID);
			imagesRegistry.put(IImagesKeys.SIGNALS_ICON, signalsIconID);
			imagesRegistry.put(IImagesKeys.CATEGORIES_ICON, categoriesIconID);
			imagesRegistry.put(IImagesKeys.LOCK_CONSOLE_ICON, lockConsoleIconID);
			imagesRegistry.put(IImagesKeys.DELETE_PROCESS_ICON, deleteProcessIconID);
			imagesRegistry.put(IImagesKeys.LIBRARY_ICON, libraryIconID);
			imagesRegistry.put(IImagesKeys.FUNCTION_ICON, functionIconID);
			imagesRegistry.put(IImagesKeys.DELETE_FUNCTION_ICON, deleteFunctionIconID);
			imagesRegistry.put(IImagesKeys.MOVE_FUNCTION_UP, moveFunctionUpIconID);
			imagesRegistry.put(IImagesKeys.MOVE_FUNCTION_DOWN, moveFunctionDownIconID);
			imagesRegistry.put(IImagesKeys.SAVE_ICON, saveIconID);
			imagesRegistry.put(IImagesKeys.SAVE_ALL_ICON, saveAllIconID);
			imagesRegistry.put(IImagesKeys.PRINT_ICON, printIconID);
			imagesRegistry.put(IImagesKeys.UNDO_ICON, undoIconID);
			imagesRegistry.put(IImagesKeys.REDO_ICON, redoIconID);
			imagesRegistry.put(IImagesKeys.CUT_ICON, cutIconID);
			imagesRegistry.put(IImagesKeys.COPY_ICON, copyIconID);
			imagesRegistry.put(IImagesKeys.PASTE_ICON, pasteIconID);
			imagesRegistry.put(IImagesKeys.DELETE_ICON, deleteIconID);
			imagesRegistry.put(IImagesKeys.RUN_ICON, runIconID);
			imagesRegistry.put(IImagesKeys.FONT_ICON, fontIconID);
			imagesRegistry.put(IImagesKeys.CONSOLE_VIEW_ICON, consoleViewIconID);
			imagesRegistry.put(IImagesKeys.CHART_OPTIONS_ICON, chartOptionsIconID);
			imagesRegistry.put(IImagesKeys.CHART_LEFT_ICON, chartLeftIconID);
			imagesRegistry.put(IImagesKeys.CHART_RIGHT_ICON, chartRightIconID);
			imagesRegistry.put(IImagesKeys.CHART_UP_ICON, chartUpIconID);
			imagesRegistry.put(IImagesKeys.CHART_DOWN_ICON, chartDownIconID);
			imagesRegistry.put(IImagesKeys.CHART_ZOOM_IN_ICON, chartZoomInIconID);
			imagesRegistry.put(IImagesKeys.CHART_ZOOM_OUT_ICON, chartZoomOutIconID);
			imagesRegistry.put(IImagesKeys.ADJUST_X_AXIS_ICON, adjustXAxisIconID);
			imagesRegistry.put(IImagesKeys.ADJUST_Y_AXIS_ICON, adjustYAxisIconID);
			imagesRegistry.put(IImagesKeys.ADJUST_XY_AXIS_ICON, adjustXYAxisIconID);
			imagesRegistry.put(IImagesKeys.CROSSHAIR_ICON, crossHairIconID);
			imagesRegistry.put(IImagesKeys.MARKER_ICON, markerIconID);
			imagesRegistry.put(IImagesKeys.ADD_MARKER_ICON, addMarkerIconID);
			imagesRegistry.put(IImagesKeys.EXPORT_WIZARD_BANNER, exportWizardBannerID);
			imagesRegistry.put(IImagesKeys.EXPORT_WIZARD_ICON, exportWizardIconID);
			imagesRegistry.put(IImagesKeys.PARAMETER_ICON, parameterIconID);
			imagesRegistry.put(IImagesKeys.KEYWORD_ICON, keywordIconID);
			imagesRegistry.put(IImagesKeys.INPUTS_ICON, inputsIconID);
			imagesRegistry.put(IImagesKeys.OUTPUTS_ICON, outputsIconID);
			imagesRegistry.put(IImagesKeys.PARAMETERS_ICON, parametersIconID);
			imagesRegistry.put(IImagesKeys.NEXT_TRIAL_ICON, nextTrialIconID);
			imagesRegistry.put(IImagesKeys.PREVIOUS_TRIAL_ICON, previousTrialIconID);
			imagesRegistry.put(IImagesKeys.NEW_PROCESS_BANNER, processBannerID);
			imagesRegistry.put(IImagesKeys.NEW_CATEGORY, newCategoryID);
			imagesRegistry.put(IImagesKeys.NEW_CATEGORY_BANNER, newCategoryBannerID);
			imagesRegistry.put(IImagesKeys.FOLDER_ICON, folderID);
			imagesRegistry.put(IImagesKeys.NEW_FOLDER_BANNER, newFolderBannerID);
			imagesRegistry.put(IImagesKeys.HELP_CONTENT_ICON, helpID);
			imagesRegistry.put(IImagesKeys.MAIN_TOPIC_ICON, mainTopicID);
			imagesRegistry.put(IImagesKeys.SUB_TOPIC_ICON, subTopicID);
			imagesRegistry.put(IImagesKeys.SUB_SUB_TOPIC_ICON, subSubTopicID);
			imagesRegistry.put(IImagesKeys.UPDATE_BANNER, updateID);
//			imagesRegistry.put(IImagesKeys.ANALYSE_ICON_SMALL, loadUnloadSubjectIconID);
			imagesRegistry.put(IImagesKeys.LOAD_UNLOAD_SUBJECT_ICON, loadUnloadSubjectIconID);
			imagesRegistry.put(IImagesKeys.REMOVE_FIELD_MARKERS_GROUP_ICON, removeFieldMarkersGroupIconID);
			imagesRegistry.put(IImagesKeys.REMOVE_MARKER_TRIAL_ICON, removeMarkerTrialIconID);
			imagesRegistry.put(IImagesKeys.CATEGORY_VIEW_ICON, categoryViewIconID);
			imagesRegistry.put(IImagesKeys.PREVIEW_VIEW_ICON, previewViewIconID);
			imagesRegistry.put(IImagesKeys.ADD_CATEGORY_ICON, addCategoryIconID);
			imagesRegistry.put(IImagesKeys.SAVE_BANNER, saveBannerID);
			imagesRegistry.put(IImagesKeys.STOP_ICON, stopIconID);
			imagesRegistry.put(IImagesKeys.REFRESH_ICON, refreshIconID);
			imagesRegistry.put(IImagesKeys.RANDOMIZE_COLOR_ICON, randomizeColorIconID);
			imagesRegistry.put(IImagesKeys.CLEAR_CHART_ICON, clearChartIconID);
			imagesRegistry.put(IImagesKeys.UPDATE_ICON, updateIconID);
			imagesRegistry.put(IImagesKeys.SHOW_EXPERIMENTS_MENU_ICON, showExperimentsMenuIconID);
			imagesRegistry.put(IImagesKeys.COLLAPSE_ALL_ICON, collapseAllIconID);
			imagesRegistry.put(IImagesKeys.EXPAND_ALL_ICON, expandAllIconID);
			imagesRegistry.put(IImagesKeys.ADD_ICON, addIconID);
			imagesRegistry.put(IImagesKeys.REFACTOR_ICON, refactorIconID);
			imagesRegistry.put(IImagesKeys.REFACTOR_BANNER, refactorBannerID);
			imagesRegistry.put(IImagesKeys.CHANGES_ICON, changesIconID);
			imagesRegistry.put(IImagesKeys.ADD_FUNCTION_ICON, addFunctionIconID);
			imagesRegistry.put(IImagesKeys.RUN_PROCESS_ICON, runProcessIconID);
			imagesRegistry.put(IImagesKeys.LOADED_SUBJECT_ICON_DECORATOR, loadedSubjectIconDecoratorID);
			imagesRegistry.put(IImagesKeys.MODIFIED_SUBJECT_ICON_DECORATOR, modifiedIconID);
			imagesRegistry.put(IImagesKeys.ERROR_ICON_DECORATOR, errorIconDecoratorID);
			imagesRegistry.put(IImagesKeys.WARNING_ICON_DECORATOR, warningIconDecoratorID);
			imagesRegistry.put(IImagesKeys.CHECK_PROCESS_ICON, checkProcessIconID);
			imagesRegistry.put(IImagesKeys.FIELD_ICON, fieldIconID);
			imagesRegistry.put(IImagesKeys.NEW_SIGNAL_ICON, newSignalIconID);
			imagesRegistry.put(IImagesKeys.CHEAT_SHEET_ICON, cheatSheetIconID);
			imagesRegistry.put(IImagesKeys.ANALYSE_IMAGE, analyseImageID);
			imagesRegistry.put(IImagesKeys.EXPERIMENTS_VIEW_IMAGE, experimentsViewImageID);
			imagesRegistry.put(IImagesKeys.SIGNALS_VIEW_IMAGE, signalsViewImageID);
			imagesRegistry.put(IImagesKeys.CATEGORIES_VIEW_IMAGE, categoriesViewImageID);
			imagesRegistry.put(IImagesKeys.PREVIEW_SIGNALS_VIEW_IMAGE, previewSignalsViewImageID);
			imagesRegistry.put(IImagesKeys.MESSAGES_VIEW_IMAGE, messagesViewImageID);
			imagesRegistry.put(IImagesKeys.CONSOLE_VIEW_IMAGE, consoleViewImageID);
			imagesRegistry.put(IImagesKeys.CHART_EDITOR_VIEW_IMAGE, chartEditorViewImageID);
			imagesRegistry.put(IImagesKeys.PROCESS_EDITOR_VIEW_IMAGE, processEditorViewImageID);
			imagesRegistry.put(IImagesKeys.EVENTS_VIEW_ICON, eventsViewIconID);
			imagesRegistry.put(IImagesKeys.AXIS_ICON, axisIconID);
			imagesRegistry.put(IImagesKeys.AXIS_BANNER, axisBannerID);
			imagesRegistry.put(IImagesKeys.NOTE_ICON, noteIconID);
			imagesRegistry.put(IImagesKeys.START_SERVER_ICON, startServerIconID);
			imagesRegistry.put(IImagesKeys.DISCONNECT_USER_ICON, disconnectUserIconID);
			imagesRegistry.put(IImagesKeys.CONNECT_SERVER_ICON, connectServerIconID);
			imagesRegistry.put(IImagesKeys.IMPORT_ICON, importIconID);
			imagesRegistry.put(IImagesKeys.SHARING_VIEW_ICON, sharingViewIconID);
			imagesRegistry.put(IImagesKeys.STOP_SERVER_ICON, stopServerIconID);
			imagesRegistry.put(IImagesKeys.EXPERIMENTS_SHARING_BANNER, experimentsSharingBannerID);
			imagesRegistry.put(IImagesKeys.FTP_USER_ICON, ftpUserIconID);
			imagesRegistry.put(IImagesKeys.FOLDER_UP_ICON, folderUpconID);
			imagesRegistry.put(IImagesKeys.FUNCTION_CONFIG, functionConfigID);
			imagesRegistry.put(IImagesKeys.FUNCTION_CODE, functionCodeID);
			imagesRegistry.put(IImagesKeys.SIGNAL_FREQUENCY_BANNER, signalFrequencyBannerID);
			imagesRegistry.put(IImagesKeys.SWITCH_LIBRARY_ICON, switchLibraryID);
			imagesRegistry.put(IImagesKeys.NEW_SUBJECT_BANNER, newSubjectBannerID);
			imagesRegistry.put(IImagesKeys.ADD_COLUMN_ICON, AddColumnIconID);
			imagesRegistry.put(IImagesKeys.DELETE_COLUMN_ICON, deleteColumnIconID);
			imagesRegistry.put(IImagesKeys.CHART_CONFIGURATION_ICON, chartConfigurationIconID);
		}
	}
	
	public static Image getImage(String key) {
		if(imagesRegistry == null) initialize(Display.getCurrent());
		return imagesRegistry.get(key);
	}
	
	public static ImageDescriptor getImageDescriptor(String key) {
		if(imagesRegistry == null) initialize(Display.getCurrent());
		return imagesRegistry.getDescriptor(key);
	}
	
	public static Image getSplashImage() {
		ImageDescriptor analyseSplashScreenID = ImageDescriptor.createFromURL(Display.getCurrent().getClass().getResource(IImagesKeys.ANALYSE_SPLASH_SCREEN));
		JFaceResources.getImageRegistry().put(IImagesKeys.ANALYSE_SPLASH_SCREEN, analyseSplashScreenID);
		return JFaceResources.getImageRegistry().get(IImagesKeys.ANALYSE_SPLASH_SCREEN);
	}
	
}

